name: My First workflow

on: 
    push


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout Repo
            uses: actions/checkout@v4

          - name: List and Read file
            run: |
                echo "My first Github Actions Job"
                ls -ltra
                cat README.md

          - name: Generate ASCII ARtwork
            run: cowsay -f dragon "Run now" >> dragon.txt


          # - name: List files
          #   run: ls
          
          # - name: Read file
          #   run: cat README.md